name: QueryFacade
main: queryfacade\QueryFacade
version: 1.1.0
api: [1.10.0, 2.0.0]
load: STARTUP
author: Gamecrafter
description: Cloak and edit your server data!
website: https://github.com/Viperize/QueryFacade-PocketMine
permissions:
 queryfacade:
  default: op
  children:
   queryfacade.command:
    default: op
    children:
     queryfacade.command.queryfacade:
      default: op
